local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {desc = '[pf] Find project file'})
vim.keymap.set('n', '<C-p>', builtin.git_files, {desc = '[C-p] Find Git file'})
vim.keymap.set('n', '<leader>pg', builtin.live_grep, {desc = '[pg] Live grep in current project'})
vim.keymap.set('n', '<leader>pb', builtin.buffers, {desc = '[pb] Select from open buffers in current project'})
vim.keymap.set('n', '<leader>ph', builtin.help_tags, {desc = '[ph] Search through help tags'})
vim.keymap.set('n', '<leader>pd', builtin.diagnostics, {desc = '[pd] Search diagnostics'})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > "), desc = '[ps] Grep search in current project' })
end)
